version: '3.5'

services:
  user_service:
    container_name: user_service
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  auth_service:
    container_name: auth_service
    build:
      context: ./authorization
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  post_service:
    container_name: post_service
    build:
      context: ./post_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  chat_service:
    container_name: chat_service
    build:
      context: ./chat_service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  postgres:
    container_name: yandex
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped


volumes:
  postgres:
