POSTGRES:
    POSTGRES_HOST: localhost
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: yandex

ROUTER:
    HTTP_HOST: localhost
    HTTP_PORT: 8080
    HTTP_READ_TIMEOUT: 10
    HTTP_WRITE_TIMEOUT: 30
    HTTP_IDLE_TIMEOUT: 60
